#!/usr/sbin/nft -f

# VARIABLES
define LAN_IF = __LAN_IF__
define WAN_IF = __WAN_IF__

flush ruleset

# MANGLE (connmark)
table ip mangle {
    chain prerouting {
        type filter hook prerouting priority mangle; policy accept;

        iifname $LAN_IF ct mark set 0xe1f1 comment "nord-router"
    }
}

# FILTER (forwarding)
table ip filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Allow loopback
        iifname "lo" accept

        # Allow established/related
        ct state established,related accept

        # Allow SSH on eth1 only
        iifname $LAN_IF tcp dport 22 accept

        # DHCP (server on eth1)
        iifname $LAN_IF udp sport 68 udp dport 67 accept
        iifname $LAN_IF udp sport 67 udp dport 68 accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        # Allow established/related return traffic
        iifname $WAN_IF oifname $LAN_IF ct state established,related accept

        # Allow outbound forwarding from eth1 → nordlynx
        iifname $LAN_IF oifname $WAN_IF accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

# NAT (masquerade)
table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        oifname $WAN_IF masquerade
    }
}
