#!/usr/bin/env bash
#
# update-issue
# Updates /etc/issue with current lan IP address.
#
# MIT License
# 
# Copyright (c) 2025 nodaddyno
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

{
    # The backslashes in the ascii art are double-escaped on purpose
    cat <<EOF
\d \t

        _   _               ___     ______  _   _
       | \\\ | | ___  _ __ __| \\\ \\\   / /  _ \\\| \\\ | |
       |  \\\| |/ _ \\\| '__/ _  |\\\ \\\ / /| |_) |  \\\| |
       | |\\\  | (_) | | | (_| | \\\ V / |  __/| |\\\  |
       |_| \\\_|\\\___/|_|  \\\__,_|  \\\_/  |_|   |_| \\\_|

              ____             _
             |  _ \\\ ___  _   _| |_ ___ _ __
             | |_) / _ \\\| | | | __/ _ \\\ '__|
             |  _ < (_) | |_| | ||  __/ |
             |_| \\\_\\\___/ \\\__,_|\\\__\\\___|_|

    Whole-network VPN router using the NordVPN Service

EOF
    # check if the webui is installed and update the displayed IP address
    if [[ -d /root/webui ]]; then
        next=0
            while read -r line; do
                if [[ $line =~ (address) ]]; then
                    next=1
                elif [[ $next -eq 1 ]]; then
                    address=${line#*- }
                    address=${address%%/*}
                fi
            done < <(cat /etc/netplan/config-lan.yaml)
        echo "Access the webui at: https://${address}:1776"
        echo
    fi
} > /etc/issue
